[package]
name = "bonacci"
version = "0.0.0"
authors = ["Leonardo Bonacci <leonardo@bonacci.com>"]
categories = ["algorithms", "mathematics"]
edition = "2024"
keywords = ["example", "fibonacci"]
license = "Unlicense"
repository = "https://github.com/leonardo/bonacci"
description = "An example Rust project for generating a Fibonacci sequence"

[dependencies]
clap = "4.6.7"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tarpaulin_include)"] }
