name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Check Crate
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4.1.7

      - name: Check Formatting
        run: cargo fmt --check
