name: Package
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Package Crate
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4.2.0

      - name: Package Crate
        run: cargo package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.1
        with:
          path: target/package/*.crate
