name: Package
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Package Crate
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4.2.2

      - name: Package Crate
        run: cargo package
