name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4.1.6

      - name: Install tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Test Package
        run: cargo tarpaulin --fail-under 45
