name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Test Crate
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Project
        uses: actions/checkout@v4.2.2

      - name: Install tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Test Crate
        run: cargo tarpaulin
